/// Hệ thống đa ngôn ngữ (Localization) cho AniApp.
///
/// Hỗ trợ 3 ngôn ngữ: Tiếng Việt ('vi'), Tiếng Anh ('en'), Tiếng Nhật ('ja').
/// Sử dụng kết hợp với [LanguageProvider] để UI tự động cập nhật khi đổi ngôn ngữ.
class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'settings': 'Cài đặt',
      'appearance_language': 'Giao diện & Ngôn ngữ',
      'dark_mode': 'Chế độ tối (Dark Mode)',
      'dark_mode_desc': 'Thay đổi giao diện ứng dụng',
      'language': 'Ngôn ngữ',
      'language_desc': 'Sử dụng để dịch thông tin anime và giao diện',
      'data_management': 'Quản lý dữ liệu (Offline)',
      'export_data': 'Xuất dữ liệu Anime',
      'export_data_desc': 'Sao chép chuỗi JSON vào Clipboard',
      'delete_all': 'Xóa toàn bộ danh sách',
      'delete_all_desc': 'Hành động này không thể hoàn tác',
      'copied_clipboard': 'Đã copy dữ liệu JSON vào Clipboard',
      'warning': 'Cảnh báo',
      'delete_confirm': 'Bạn có chắc muốn xóa toàn bộ danh sách anime cá nhân không? Hành động này không thể hoàn tác.',
      'cancel': 'Hủy',
      'delete': 'Xóa',
      'deleted_all': 'Đã xóa toàn bộ dữ liệu',
      'language_changed': 'Đã thay đổi ngôn ngữ thành công!',
      'offline_banner': 'Mất kết nối mạng. Bạn đang xem dữ liệu Offline.',
      // Main Nav
      'nav_home': 'Trang chủ',
      'nav_search': 'Tìm kiếm',
      'nav_mylist': 'Danh sách',
      'nav_profile': 'Cá nhân',
      // InfoScreen
      'profile_title': 'Cá nhân & Thống kê',
      'total_anime': 'Tổng Anime',
      'episodes_watched': 'Số tập đã xem',
      'avg_score': 'Điểm trung bình',
      'edit_info': 'Chỉnh sửa thông tin',
      'status_watching': 'Đang xem',
      'status_completed': 'Đã xem',
      'status_plan': 'Dự định',
      'status_dropped': 'Bỏ dở',
      'status_on_hold': 'Tạm dừng',
      // DetailScreen
      'trailer_title': 'Trailer / Video giới thiệu:',
      'synopsis_title': 'Nội dung chính:',
      'status': 'Trạng thái:',
      'aired': 'Lịch phát sóng:',
      'duration': 'Thời lượng:',
      'rating': 'Độ tuổi:',
      'source': 'Nguồn gốc:',
      'background_title': 'Bối cảnh / Thông tin thêm:',
      'no_trailer': 'Phim này chưa có video trailer.',
      'no_background': 'Không có thông tin bối cảnh từ MyAnimeList.',
      'translating': 'Đang dịch...',
      'translation_error': 'Lỗi dịch thuật',
      // HomeScreen
      'seasons_now': 'Đang chiếu mùa này',
      'top_anime': 'Top Anime',
      'upcoming': 'Sắp ra mắt',
      // SearchScreen
      'search_hint': 'Tìm kiếm anime...',
      'trending_now': 'Đang thịnh hành',
      'seasonal': 'Anime theo mùa',
      'recently_updated': 'Mới cập nhật / Sắp ra mắt',
      // MyListScreen
      'my_list_title': 'Danh sách của tôi',
      'filter_all': 'Tất cả',
      'progress': 'Tiến độ',
      'score': 'Điểm',
      // BottomSheet & FAB
      'add_to_list': 'Thêm vào danh sách',
      'added_to_list': 'Đã thêm vào danh sách',
      'update_progress': 'Cập nhật tiến độ:',
      'status_label': 'Trạng thái',
      'episodes_watched_label': 'Số tập đã xem',
      'rating_label': 'Đánh giá (1-10 sao)',
      'personal_note': 'Ghi chú cá nhân',
      'save_info': 'Lưu thông tin',
      'saved_success': 'Đã lưu vào danh sách!',
      'invalid_episodes': 'Vui lòng nhập số tập hợp lệ',
      // Edit Profile
      'update_success': 'Cập nhật thông tin thành công',
      'edit_profile': 'Cập nhật hồ sơ',
      'avatar': 'Ảnh đại diện',
      'choose_avatar': 'Hoặc chọn Avatar có sẵn:',
      'general_info': 'Thông tin chung',
      'display_name': 'Tên hiển thị',
      'name_required': 'Vui lòng nhập tên hiển thị',
      'name_min_length': 'Tên phải chứa ít nhất 3 ký tự',
      'email': 'Email',
      'email_required': 'Vui lòng nhập email',
      'email_invalid': 'Email không hợp lệ',
      'change_password': 'Đổi mật khẩu (Tùy chọn)',
      'password_hint': 'Nhập mật khẩu hiện tại nếu bạn muốn thay đổi Email hoặc Mật khẩu.',
      'current_password': 'Mật khẩu hiện tại',
      'new_password': 'Mật khẩu mới',
      'password_min_length': 'Mật khẩu mới phải có ít nhất 6 ký tự',
      'save_changes': 'Lưu thay đổi',
      // Info / Stats
      'confirm': 'Xác nhận',
      'logout_confirm': 'Bạn có muốn đăng xuất khỏi tài khoản này?',
      'logout': 'Đăng xuất',
      'stats_error': 'Lỗi tải thống kê:',
      'not_logged_in': 'Bạn chưa đăng nhập',
      'login_prompt': 'Đăng nhập để đồng bộ dữ liệu và sử dụng thêm nhiều tính năng',
      'register': 'Đăng ký',
      'login': 'Đăng nhập',
      'personal_stats': 'Thống kê cá nhân',
      'theme_toggle': 'Đổi giao diện (Dark/Light)',

      'status_distribution': 'Phân bổ trạng thái',
      // MyList Extra & Search
      'updates_found': 'Đã tìm thấy cập nhật mới! Kiểm tra thông báo.',
      'no_updates': 'Không có cập nhật mới nào.',
      'check_updates': 'Kiểm tra cập nhật',
      'empty_list': 'Danh sách trống',
      'deleted': 'Đã xóa',
      'error_occurred': 'Đã xảy ra lỗi:',
      'no_anime_found': 'Không tìm thấy anime nào',
      'load_error': 'Lỗi tải dữ liệu',
      // Auth
      'register_success': 'Đăng ký thành công!',
      'register_title': 'Đăng ký tài khoản',
      'login_title': 'Đăng nhập để tiếp tục',
      'password': 'Mật khẩu',
      'password_required': 'Vui lòng nhập Mật khẩu',
      'password_min_length_auth': 'Mật khẩu phải từ 6 ký tự trở lên',
      'confirm_password': 'Xác nhận mật khẩu',
      'confirm_password_required': 'Vui lòng xác nhận mật khẩu',
      'password_mismatch': 'Mật khẩu không khớp',
      'no_account': 'Chưa có tài khoản? Đăng ký ngay',
      // Auth Errors
      'err_invalid_credentials': 'Email hoặc mật khẩu không chính xác',
      'err_system': 'Lỗi hệ thống:',
      'err_email_exists': 'Email này đã được đăng ký',
      'err_user_not_found': 'Không tìm thấy người dùng',
      'err_need_current_password': 'Vui lòng nhập mật khẩu hiện tại để thay đổi Email/Mật khẩu',
      'err_wrong_current_password': 'Mật khẩu hiện tại không đúng',
      'err_email_in_use': 'Email này đã được sử dụng bởi tài khoản khác',
    },
    'en': {
      'settings': 'Settings',
      'appearance_language': 'Appearance & Language',
      'dark_mode': 'Dark Mode',
      'dark_mode_desc': 'Change the app appearance',
      'language': 'Language',
      'language_desc': 'Used to translate anime info and system UI',
      'data_management': 'Data Management (Offline)',
      'export_data': 'Export Anime Data',
      'export_data_desc': 'Copy JSON string to Clipboard',
      'delete_all': 'Delete All Data',
      'delete_all_desc': 'This action cannot be undone',
      'copied_clipboard': 'Copied JSON data to Clipboard',
      'warning': 'Warning',
      'delete_confirm': 'Are you sure you want to delete all personal anime data? This action cannot be undone.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'deleted_all': 'All data deleted successfully',
      'language_changed': 'Language changed successfully!',
      'offline_banner': 'No internet connection. You are viewing Offline data.',
      // Main Nav
      'nav_home': 'Home',
      'nav_search': 'Search',
      'nav_mylist': 'My List',
      'nav_profile': 'Profile',
      // InfoScreen
      'profile_title': 'Profile & Stats',
      'total_anime': 'Total Anime',
      'episodes_watched': 'Episodes Watched',
      'avg_score': 'Avg Score',
      'edit_info': 'Edit Information',
      'status_watching': 'Watching',
      'status_completed': 'Completed',
      'status_plan': 'Plan to Watch',
      'status_dropped': 'Dropped',
      'status_on_hold': 'On Hold',
      // DetailScreen
      'trailer_title': 'Trailer / Promotional Video:',
      'synopsis_title': 'Synopsis:',
      'status': 'Status:',
      'aired': 'Aired:',
      'duration': 'Duration:',
      'rating': 'Rating:',
      'source': 'Source:',
      'background_title': 'Background / Extra Info:',
      'no_trailer': 'This anime does not have a trailer.',
      'no_background': 'No background info from MyAnimeList.',
      'translating': 'Translating...',
      'translation_error': 'Translation Error',
      // HomeScreen
      'seasons_now': 'Airing this Season',
      'top_anime': 'Top Anime',
      'upcoming': 'Upcoming',
      // SearchScreen
      'search_hint': 'Search anime...',
      'trending_now': 'Trending Now',
      'seasonal': 'Seasonal',
      'recently_updated': 'Recently Updated / Upcoming',
      // MyListScreen
      'my_list_title': 'My List',
      'filter_all': 'All',
      'progress': 'Progress',
      'score': 'Score',
      // BottomSheet & FAB
      'add_to_list': 'Add to List',
      'added_to_list': 'Added to List',
      'update_progress': 'Update Progress:',
      'status_label': 'Status',
      'episodes_watched_label': 'Episodes Watched',
      'rating_label': 'Rating (1-10 stars)',
      'personal_note': 'Personal Note',
      'save_info': 'Save Information',
      'saved_success': 'Saved to list!',
      'invalid_episodes': 'Please enter a valid episode number',
      // Edit Profile
      'update_success': 'Profile updated successfully',
      'edit_profile': 'Edit Profile',
      'avatar': 'Avatar',
      'choose_avatar': 'Or choose an available Avatar:',
      'general_info': 'General Information',
      'display_name': 'Display Name',
      'name_required': 'Please enter display name',
      'name_min_length': 'Name must be at least 3 characters',
      'email': 'Email',
      'email_required': 'Please enter email',
      'email_invalid': 'Invalid email',
      'change_password': 'Change Password (Optional)',
      'password_hint': 'Enter current password if you want to change Email or Password.',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'password_min_length': 'New password must be at least 6 characters',
      'save_changes': 'Save Changes',
      // Info / Stats
      'confirm': 'Confirm',
      'logout_confirm': 'Do you want to log out of this account?',
      'logout': 'Log Out',
      'stats_error': 'Error loading stats:',
      'not_logged_in': 'You are not logged in',
      'login_prompt': 'Log in to sync data and use more features',
      'register': 'Register',
      'login': 'Log In',
      'personal_stats': 'Personal Stats',
      'theme_toggle': 'Toggle Theme (Dark/Light)',

      'status_distribution': 'Status Distribution',
      // MyList Extra & Search
      'updates_found': 'Updates found! Check notifications.',
      'no_updates': 'No new updates.',
      'check_updates': 'Check for updates',
      'empty_list': 'Empty list',
      'deleted': 'Deleted',
      'error_occurred': 'An error occurred:',
      'no_anime_found': 'No anime found',
      'load_error': 'Data loading error',
      // Auth
      'register_success': 'Registration successful!',
      'register_title': 'Create an Account',
      'login_title': 'Log in to continue',
      'password': 'Password',
      'password_required': 'Please enter password',
      'password_min_length_auth': 'Password must be at least 6 characters',
      'confirm_password': 'Confirm Password',
      'confirm_password_required': 'Please confirm password',
      'password_mismatch': 'Passwords do not match',
      'no_account': 'Don\'t have an account? Register now',
      // Auth Errors
      'err_invalid_credentials': 'Incorrect email or password',
      'err_system': 'System error:',
      'err_email_exists': 'This email is already registered',
      'err_user_not_found': 'User not found',
      'err_need_current_password': 'Please enter current password to change Email/Password',
      'err_wrong_current_password': 'Incorrect current password',
      'err_email_in_use': 'This email is already in use by another account',
    },
    'ja': {
      'settings': '設定',
      'appearance_language': '外観と言語',
      'dark_mode': 'ダークモード',
      'dark_mode_desc': 'アプリの外観を変更します',
      'language': '言語',
      'language_desc': 'アニメ情報とシステムUIの翻訳に使用されます',
      'data_management': 'データ管理 (オフライン)',
      'export_data': 'アニメデータをエクスポート',
      'export_data_desc': 'JSON文字列をクリップボードにコピー',
      'delete_all': 'すべてのデータを削除',
      'delete_all_desc': 'この操作は元に戻せません',
      'copied_clipboard': 'JSONデータをクリップボードにコピーしました',
      'warning': '警告',
      'delete_confirm': 'すべてのアニメデータを削除してもよろしいですか？この操作は元に戻せません。',
      'cancel': 'キャンセル',
      'delete': '削除',
      'deleted_all': 'すべてのデータが正常に削除されました',
      'language_changed': '言語が正常に変更されました！',
      'offline_banner': 'インターネット接続がありません。オフラインデータを表示しています。',
      // Main Nav
      'nav_home': 'ホーム',
      'nav_search': '検索',
      'nav_mylist': 'マイリスト',
      'nav_profile': 'プロフィール',
      // InfoScreen
      'profile_title': 'プロフィールと統計',
      'total_anime': 'アニメ合計',
      'episodes_watched': '視聴エピソード',
      'avg_score': '平均スコア',
      'edit_info': '情報を編集',
      'status_watching': '視聴中',
      'status_completed': '完了',
      'status_plan': '予定',
      'status_dropped': 'ドロップ',
      'status_on_hold': '保留',
      // DetailScreen
      'trailer_title': '予告編 / プロモーションビデオ:',
      'synopsis_title': 'あらすじ:',
      'status': 'ステータス:',
      'aired': '放送日:',
      'duration': '期間:',
      'rating': '年齢制限:',
      'source': '原作:',
      'background_title': '背景情報:',
      'no_trailer': 'このアニメには予告編がありません。',
      'no_background': 'MyAnimeListからの背景情報はありません。',
      'translating': '翻訳中...',
      'translation_error': '翻訳エラー',
      // HomeScreen
      'seasons_now': '今期放送中',
      'top_anime': 'トップアニメ',
      'upcoming': '近日公開',
      // SearchScreen
      'search_hint': 'アニメを検索...',
      'trending_now': 'トレンド',
      'seasonal': '季節のアニメ',
      'recently_updated': '最近の更新 / 近日公開',
      // MyListScreen
      'my_list_title': 'マイリスト',
      'filter_all': 'すべて',
      'progress': '進捗',
      'score': 'スコア',
      // BottomSheet & FAB
      'add_to_list': 'リストに追加',
      'added_to_list': 'リストに追加済み',
      'update_progress': '進捗を更新:',
      'status_label': 'ステータス',
      'episodes_watched_label': '視聴したエピソード',
      'rating_label': '評価 (1-10星)',
      'personal_note': '個人的なメモ',
      'save_info': '情報を保存',
      'saved_success': 'リストに保存しました！',
      'invalid_episodes': '有効なエピソード数を入力してください',
      // Edit Profile
      'update_success': 'プロフィールが更新されました',
      'edit_profile': 'プロフィール編集',
      'avatar': 'アバター',
      'choose_avatar': 'または利用可能なアバターを選択:',
      'general_info': '一般情報',
      'display_name': '表示名',
      'name_required': '表示名を入力してください',
      'name_min_length': '名前は3文字以上である必要があります',
      'email': 'メール',
      'email_required': 'メールを入力してください',
      'email_invalid': '無効なメールアドレス',
      'change_password': 'パスワードの変更（任意）',
      'password_hint': 'メールまたはパスワードを変更する場合は現在のパスワードを入力してください。',
      'current_password': '現在のパスワード',
      'new_password': '新しいパスワード',
      'password_min_length': '新しいパスワードは6文字以上である必要があります',
      'save_changes': '変更を保存',
      // Info / Stats
      'confirm': '確認',
      'logout_confirm': 'このアカウントからログアウトしますか？',
      'logout': 'ログアウト',
      'stats_error': '統計の読み込みエラー:',
      'not_logged_in': 'ログインしていません',
      'login_prompt': 'データを同期し、より多くの機能を使用するにはログインしてください',
      'register': '登録',
      'login': 'ログイン',
      'personal_stats': '個人統計',
      'theme_toggle': 'テーマの切り替え（ダーク/ライト）',

      'status_distribution': 'ステータス分布',
      // MyList Extra & Search
      'updates_found': '更新が見つかりました！通知を確認してください。',
      'no_updates': '新しい更新はありません。',
      'check_updates': '更新を確認',
      'empty_list': 'リストが空です',
      'deleted': '削除しました',
      'error_occurred': 'エラーが発生しました:',
      'no_anime_found': 'アニメが見つかりません',
      'load_error': 'データの読み込みエラー',
      // Auth
      'register_success': '登録に成功しました！',
      'register_title': 'アカウント作成',
      'login_title': 'ログインして続行',
      'password': 'パスワード',
      'password_required': 'パスワードを入力してください',
      'password_min_length_auth': 'パスワードは6文字以上である必要があります',
      'confirm_password': 'パスワードの確認',
      'confirm_password_required': 'パスワードを確認してください',
      'password_mismatch': 'パスワードが一致しません',
      'no_account': 'アカウントを持っていませんか？ 今すぐ登録',
      // Auth Errors
      'err_invalid_credentials': 'メールアドレスまたはパスワードが正しくありません',
      'err_system': 'システムエラー:',
      'err_email_exists': 'このメールアドレスは既に登録されています',
      'err_user_not_found': 'ユーザーが見つかりません',
      'err_need_current_password': 'メール/パスワードを変更するには、現在のパスワードを入力してください',
      'err_wrong_current_password': '現在のパスワードが間違っています',
      'err_email_in_use': 'このメールアドレスは他のアカウントで既に使用されています',
    }
  };

  static String get(String langCode, String key) {
    if (_localizedValues.containsKey(langCode) && _localizedValues[langCode]!.containsKey(key)) {
      return _localizedValues[langCode]![key]!;
    }
    // Fallback to Vietnamese if not found
    return _localizedValues['vi']?[key] ?? key;
  }
}
